services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketlab
      # POSTGRES_HOST: localhost
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: marketlab-task
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      # - "80:80"
      # - "443:443"
    restart: always

  
volumes:
  postgres-data:
    name: marketlab-task-docker-db
